name: Whiskee
title: Whiskee Blogs
description: Warehouse of 
  Hyperactive 
  Ideas 
  Spanning 
  Knowledge 
  Extracted from the 
  Endless valley of caffeine-infused, boredom-amplified, curiosity
tags:
  - blog
  - ideas
  - stories
  - random
  - science
  - technology
  - philosophy
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: 
# See: https://disqus.com/
disqus_username: 
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: 
